# Numpy

In [1]:
# Numpy Library
import numpy as np

Import Finance Data (Historical Prices)

In [2]:
import warnings
warnings.filterwarnings("ignore")

# fix_yahoo_finance is used to fetch data 
import fix_yahoo_finance as yf
yf.pdr_override()

In [3]:
# input
symbol = 'AMD'
start = '2014-01-01'
end = '2018-08-27'

# Read data 
dataset = yf.download(symbol,start,end)

# View Columns
dataset.head()

[*********************100%***********************]  1 of 1 downloaded


Open  High   Low  Close  Adj Close    Volume
Date                                                    
2014-01-02  3.85  3.98  3.84   3.95       3.95  20548400
2014-01-03  3.98  4.00  3.88   4.00       4.00  22887200
2014-01-06  4.01  4.18  3.99   4.13       4.13  42398300
2014-01-07  4.19  4.25  4.11   4.18       4.18  42932100
2014-01-08  4.23  4.26  4.14   4.18       4.18  30678700

In [4]:
# Convert dataset to numpy
# Convert Open dataframe to array
Open_array = np.array(dataset['Open'])
Open_array  

array([  3.85    ,   3.98    ,   4.01    , ...,  21.190001,  22.91    ,
        24.940001])

In [5]:
print("First element:", Open_array [0])
print("Second element:", Open_array [1])
print("Second last element:", Open_array[-1])

First element: 3.85
Second element: 3.98
Second last element: 24.940001


In [6]:
print(Open_array[2:5]) # 3rd to 5th
print(Open_array[:-5]) # beginning to 4th
print(Open_array[5:])  # 6th to end
print(Open_array[:])   # beginning to end

[ 4.01  4.19  4.23]
[  3.85       3.98       4.01     ...,  19.860001  19.120001  19.790001]
[  4.2        4.09       4.19     ...,  21.190001  22.91      24.940001]
[  3.85       3.98       4.01     ...,  21.190001  22.91      24.940001]


In [7]:
volume = np.array(dataset['Volume'])

# changing first element
volume[0] = 0    
print(volume)  

[        0  22887200  42398300 ..., 113444100 164328200 325058400]


In [8]:
# changing 3rd to 5th element
volume[2:5] = np.array([4, 6, 8])   
print(volume)       

[        0  22887200         4 ..., 113444100 164328200 325058400]


In [9]:
# Add Elements
add_numbers = np.array([1, 2, 3])

np.concatenate((volume, add_numbers))

array([       0, 22887200,        4, ...,        1,        2,        3])

In [10]:
np.append(volume, add_numbers, axis=0)

array([       0, 22887200,        4, ...,        1,        2,        3])

In [11]:
# Remove elements
print(volume)

[        0  22887200         4 ..., 113444100 164328200 325058400]


In [12]:
np.delete(volume, 1) # delete the 2nd element

array([        0,         4,         6, ..., 113444100, 164328200,
       325058400])

In [13]:
volume = volume.tolist() # Convert tolist() to use remove
volume

[0,
 22887200,
 4,
 6,
 8,
 30667600,
 20840800,
 22856100,
 42434800,
 66613100,
 46975600,
 45842700,
 58702900,
 86329500,
 29844700,
 48095800,
 31332300,
 27962600,
 21765000,
 17111700,
 13602100,
 22280200,
 22681000,
 14858900,
 16072900,
 23119700,
 21241100,
 34198100,
 18321300,
 13368600,
 12387900,
 11956700,
 14175500,
 13276100,
 13606800,
 10717900,
 9173500,
 13211700,
 18218000,
 14643200,
 19555800,
 10516100,
 10740200,
 10713000,
 55435800,
 42135800,
 34951400,
 14700500,
 19803000,
 18161500,
 20004100,
 15273700,
 28516900,
 23600600,
 23871200,
 20669500,
 14517000,
 14799700,
 24532000,
 13189200,
 15386000,
 18778800,
 14839500,
 16802300,
 23427000,
 24874600,
 17339100,
 11270300,
 21364300,
 34428800,
 22735100,
 21754300,
 18173300,
 32048100,
 102651500,
 52806800,
 29136300,
 27532800,
 37810200,
 31737100,
 14582900,
 18419200,
 37807300,
 14479700,
 9015400,
 17929300,
 22374700,
 14550200,
 15982900,
 14785500,
 11224000,
 10349600,
 18000900,
 17166

In [14]:
volume.remove(0)
print(volume)

[22887200, 4, 6, 8, 30667600, 20840800, 22856100, 42434800, 66613100, 46975600, 45842700, 58702900, 86329500, 29844700, 48095800, 31332300, 27962600, 21765000, 17111700, 13602100, 22280200, 22681000, 14858900, 16072900, 23119700, 21241100, 34198100, 18321300, 13368600, 12387900, 11956700, 14175500, 13276100, 13606800, 10717900, 9173500, 13211700, 18218000, 14643200, 19555800, 10516100, 10740200, 10713000, 55435800, 42135800, 34951400, 14700500, 19803000, 18161500, 20004100, 15273700, 28516900, 23600600, 23871200, 20669500, 14517000, 14799700, 24532000, 13189200, 15386000, 18778800, 14839500, 16802300, 23427000, 24874600, 17339100, 11270300, 21364300, 34428800, 22735100, 21754300, 18173300, 32048100, 102651500, 52806800, 29136300, 27532800, 37810200, 31737100, 14582900, 18419200, 37807300, 14479700, 9015400, 17929300, 22374700, 14550200, 15982900, 14785500, 11224000, 10349600, 18000900, 17166600, 18171000, 15647500, 13369500, 11903100, 9831100, 6922800, 12293800, 8876700, 10030600, 1085

In [15]:
print(volume.pop(2))   # Output: 12
print(volume)

6
[22887200, 4, 8, 30667600, 20840800, 22856100, 42434800, 66613100, 46975600, 45842700, 58702900, 86329500, 29844700, 48095800, 31332300, 27962600, 21765000, 17111700, 13602100, 22280200, 22681000, 14858900, 16072900, 23119700, 21241100, 34198100, 18321300, 13368600, 12387900, 11956700, 14175500, 13276100, 13606800, 10717900, 9173500, 13211700, 18218000, 14643200, 19555800, 10516100, 10740200, 10713000, 55435800, 42135800, 34951400, 14700500, 19803000, 18161500, 20004100, 15273700, 28516900, 23600600, 23871200, 20669500, 14517000, 14799700, 24532000, 13189200, 15386000, 18778800, 14839500, 16802300, 23427000, 24874600, 17339100, 11270300, 21364300, 34428800, 22735100, 21754300, 18173300, 32048100, 102651500, 52806800, 29136300, 27532800, 37810200, 31737100, 14582900, 18419200, 37807300, 14479700, 9015400, 17929300, 22374700, 14550200, 15982900, 14785500, 11224000, 10349600, 18000900, 17166600, 18171000, 15647500, 13369500, 11903100, 9831100, 6922800, 12293800, 8876700, 10030600, 10859