# Python Matrix

In [5]:
# Numpy Library
import numpy as np # for matrix and linear algebra

In [1]:
import warnings
warnings.filterwarnings("ignore")

# fix_yahoo_finance is used to fetch data 
import fix_yahoo_finance as yf
yf.pdr_override()

In [10]:
# input
symbol = 'AMD'
start = '2018-01-01'
end = '2018-01-31'

# Read data 
dataset = yf.download(symbol,start,end)

# View Columns
dataset.head()

[*********************100%***********************]  1 of 1 downloaded


Open   High    Low  Close  Adj Close     Volume
Date                                                        
2018-01-02  10.42  11.02  10.34  10.98      10.98   44146300
2018-01-03  11.61  12.14  11.36  11.55      11.55  154066700
2018-01-04  12.10  12.43  11.97  12.12      12.12  109503000
2018-01-05  12.19  12.22  11.66  11.88      11.88   63808900
2018-01-08  12.01  12.30  11.85  12.28      12.28   63346000

In [12]:
df = dataset.drop(['High', 'Low', 'Close', 'Volume'], axis=1)

In [14]:
df.head()

Open  Adj Close
Date                        
2018-01-02  10.42      10.98
2018-01-03  11.61      11.55
2018-01-04  12.10      12.12
2018-01-05  12.19      11.88
2018-01-08  12.01      12.28

In [13]:
A = np.array(df)
A

array([[ 10.42,  10.98],
       [ 11.61,  11.55],
       [ 12.1 ,  12.12],
       [ 12.19,  11.88],
       [ 12.01,  12.28],
       [ 12.  ,  11.82],
       [ 11.63,  11.96],
       [ 12.07,  12.14],
       [ 11.82,  12.02],
       [ 12.05,  11.91],
       [ 11.9 ,  12.18],
       [ 12.18,  12.47],
       [ 12.56,  12.59],
       [ 12.61,  12.65],
       [ 12.82,  12.94],
       [ 13.02,  12.71],
       [ 12.78,  12.41],
       [ 12.7 ,  12.95],
       [ 13.13,  13.32],
       [ 13.12,  12.87],
       [ 13.24,  13.74]])

In [16]:
print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][1])   # 2nd element of 2nd row
print("A[0][-1] =", A[0][-1]) 

A = [[ 10.42  10.98]
 [ 11.61  11.55]
 [ 12.1   12.12]
 [ 12.19  11.88]
 [ 12.01  12.28]
 [ 12.    11.82]
 [ 11.63  11.96]
 [ 12.07  12.14]
 [ 11.82  12.02]
 [ 12.05  11.91]
 [ 11.9   12.18]
 [ 12.18  12.47]
 [ 12.56  12.59]
 [ 12.61  12.65]
 [ 12.82  12.94]
 [ 13.02  12.71]
 [ 12.78  12.41]
 [ 12.7   12.95]
 [ 13.13  13.32]
 [ 13.12  12.87]
 [ 13.24  13.74]]
A[1] = [ 11.61  11.55]
A[1][2] = 11.55
A[0][-1] = 10.98


In [19]:
column = [];        # empty list
for row in A:
  column.append(row[1]) 

print("Second column =", column)

Second column = [10.98, 11.550000000000001, 12.119999999999999, 11.880000000000001, 12.279999999999999, 11.82, 11.960000000000001, 12.140000000000001, 12.02, 11.91, 12.18, 12.470000000000001, 12.59, 12.65, 12.94, 12.710000000000001, 12.41, 12.949999999999999, 13.32, 12.869999999999999, 13.74]


In [20]:
type(A)

numpy.ndarray

In [41]:
# Example of arange and shape()
A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [42]:
A = np.array(dataset['High'], dataset['Low'])
B = np.array(dataset['Open'], dataset['Close'])

In [47]:
C = A + B
print("Addition Matrix: \n", C)

Addition Matrix: 
 [ 21.44  23.75  24.53  24.41  24.31  24.02  23.78  24.26  23.89  24.25
  24.09  24.86  25.44  25.35  25.82  26.07  25.72  25.65  26.6   26.39
  27.09]


In [48]:
D = A - B
print("Subtraction Matrix: \n", D)

Subtraction Matrix: 
 [ 0.6   0.53  0.33  0.03  0.29  0.02  0.52  0.12  0.25  0.15  0.29  0.5
  0.32  0.13  0.18  0.03  0.16  0.25  0.34  0.15  0.61]


In [49]:
# Multiplication of Two Matrices
E = A.dot(B)
print("Multiplication of Two Matrices: \n", E)

Multiplication of Two Matrices: 
 3247.8911


In [50]:
T = A.transpose()
print("Transpose of a Matrix: \n", T)

Transpose of a Matrix: 
 [ 11.02  12.14  12.43  12.22  12.3   12.02  12.15  12.19  12.07  12.2
  12.19  12.68  12.88  12.74  13.    13.05  12.94  12.95  13.47  13.27
  13.85]


In [51]:
# Access matrix elements, rows, and columns

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element    

A[0] = 11.02
A[2] = 12.43
A[-1] = 13.85


In [59]:
A = np.array(dataset[['Open', 'Low', 'High', 'Close']])

print("Matrix of A: \n", A)
#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1])  

Matrix of A: 
 [[ 10.42  10.34  11.02  10.98]
 [ 11.61  11.36  12.14  11.55]
 [ 12.1   11.97  12.43  12.12]
 [ 12.19  11.66  12.22  11.88]
 [ 12.01  11.85  12.3   12.28]
 [ 12.    11.71  12.02  11.82]
 [ 11.63  11.56  12.15  11.96]
 [ 12.07  11.9   12.19  12.14]
 [ 11.82  11.8   12.07  12.02]
 [ 12.05  11.8   12.2   11.91]
 [ 11.9   11.82  12.19  12.18]
 [ 12.18  12.15  12.68  12.47]
 [ 12.56  12.54  12.88  12.59]
 [ 12.61  12.37  12.74  12.65]
 [ 12.82  12.76  13.    12.94]
 [ 13.02  12.6   13.05  12.71]
 [ 12.78  12.32  12.94  12.41]
 [ 12.7   12.62  12.95  12.95]
 [ 13.13  13.05  13.47  13.32]
 [ 13.12  12.69  13.27  12.87]
 [ 13.24  13.15  13.85  13.74]]
A[0][0] = 10.42
A[1][2] = 12.14
A[-1][-1] = 13.74


In [60]:
# Access rows of a Matrix

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 10.42  10.34  11.02  10.98]
A[2] = [ 12.1   11.97  12.43  12.12]
A[-1] = [ 13.24  13.15  13.85  13.74]


In [61]:
# Access columns of a Matrix

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 10.42  11.61  12.1   12.19  12.01  12.    11.63  12.07  11.82  12.05
  11.9   12.18  12.56  12.61  12.82  13.02  12.78  12.7   13.13  13.12
  13.24]
A[:,3] = [ 10.98  11.55  12.12  11.88  12.28  11.82  11.96  12.14  12.02  11.91
  12.18  12.47  12.59  12.65  12.94  12.71  12.41  12.95  13.32  12.87
  13.74]
A[:,-1] = [ 10.98  11.55  12.12  11.88  12.28  11.82  11.96  12.14  12.02  11.91
  12.18  12.47  12.59  12.65  12.94  12.71  12.41  12.95  13.32  12.87
  13.74]


In [63]:
# 3rd to 5th elements
print(A[2:5])        

[[ 12.1   11.97  12.43  12.12]
 [ 12.19  11.66  12.22  11.88]
 [ 12.01  11.85  12.3   12.28]]


In [64]:
# 1st to 4th elements
print(A[:-5])        

[[ 10.42  10.34  11.02  10.98]
 [ 11.61  11.36  12.14  11.55]
 [ 12.1   11.97  12.43  12.12]
 [ 12.19  11.66  12.22  11.88]
 [ 12.01  11.85  12.3   12.28]
 [ 12.    11.71  12.02  11.82]
 [ 11.63  11.56  12.15  11.96]
 [ 12.07  11.9   12.19  12.14]
 [ 11.82  11.8   12.07  12.02]
 [ 12.05  11.8   12.2   11.91]
 [ 11.9   11.82  12.19  12.18]
 [ 12.18  12.15  12.68  12.47]
 [ 12.56  12.54  12.88  12.59]
 [ 12.61  12.37  12.74  12.65]
 [ 12.82  12.76  13.    12.94]
 [ 13.02  12.6   13.05  12.71]]


In [65]:
# 6th to last elements
print(A[5:])    

[[ 12.    11.71  12.02  11.82]
 [ 11.63  11.56  12.15  11.96]
 [ 12.07  11.9   12.19  12.14]
 [ 11.82  11.8   12.07  12.02]
 [ 12.05  11.8   12.2   11.91]
 [ 11.9   11.82  12.19  12.18]
 [ 12.18  12.15  12.68  12.47]
 [ 12.56  12.54  12.88  12.59]
 [ 12.61  12.37  12.74  12.65]
 [ 12.82  12.76  13.    12.94]
 [ 13.02  12.6   13.05  12.71]
 [ 12.78  12.32  12.94  12.41]
 [ 12.7   12.62  12.95  12.95]
 [ 13.13  13.05  13.47  13.32]
 [ 13.12  12.69  13.27  12.87]
 [ 13.24  13.15  13.85  13.74]]


In [66]:
# 1st to last elements
print(A[:])    

[[ 10.42  10.34  11.02  10.98]
 [ 11.61  11.36  12.14  11.55]
 [ 12.1   11.97  12.43  12.12]
 [ 12.19  11.66  12.22  11.88]
 [ 12.01  11.85  12.3   12.28]
 [ 12.    11.71  12.02  11.82]
 [ 11.63  11.56  12.15  11.96]
 [ 12.07  11.9   12.19  12.14]
 [ 11.82  11.8   12.07  12.02]
 [ 12.05  11.8   12.2   11.91]
 [ 11.9   11.82  12.19  12.18]
 [ 12.18  12.15  12.68  12.47]
 [ 12.56  12.54  12.88  12.59]
 [ 12.61  12.37  12.74  12.65]
 [ 12.82  12.76  13.    12.94]
 [ 13.02  12.6   13.05  12.71]
 [ 12.78  12.32  12.94  12.41]
 [ 12.7   12.62  12.95  12.95]
 [ 13.13  13.05  13.47  13.32]
 [ 13.12  12.69  13.27  12.87]
 [ 13.24  13.15  13.85  13.74]]


In [67]:
# reversing a list
print(A[::-1])     

[[ 13.24  13.15  13.85  13.74]
 [ 13.12  12.69  13.27  12.87]
 [ 13.13  13.05  13.47  13.32]
 [ 12.7   12.62  12.95  12.95]
 [ 12.78  12.32  12.94  12.41]
 [ 13.02  12.6   13.05  12.71]
 [ 12.82  12.76  13.    12.94]
 [ 12.61  12.37  12.74  12.65]
 [ 12.56  12.54  12.88  12.59]
 [ 12.18  12.15  12.68  12.47]
 [ 11.9   11.82  12.19  12.18]
 [ 12.05  11.8   12.2   11.91]
 [ 11.82  11.8   12.07  12.02]
 [ 12.07  11.9   12.19  12.14]
 [ 11.63  11.56  12.15  11.96]
 [ 12.    11.71  12.02  11.82]
 [ 12.01  11.85  12.3   12.28]
 [ 12.19  11.66  12.22  11.88]
 [ 12.1   11.97  12.43  12.12]
 [ 11.61  11.36  12.14  11.55]
 [ 10.42  10.34  11.02  10.98]]


In [68]:
print(A[:2, :4])  # two rows, four columns

[[ 10.42  10.34  11.02  10.98]
 [ 11.61  11.36  12.14  11.55]]


In [69]:
print(A[:1,])  # first row, all columns

[[ 10.42  10.34  11.02  10.98]]


In [70]:
print(A[:,2])  # all rows, second column

[ 11.02  12.14  12.43  12.22  12.3   12.02  12.15  12.19  12.07  12.2
  12.19  12.68  12.88  12.74  13.    13.05  12.94  12.95  13.47  13.27
  13.85]


In [71]:
print(A[:, 2:5])  # all rows, third to fifth column

[[ 11.02  10.98]
 [ 12.14  11.55]
 [ 12.43  12.12]
 [ 12.22  11.88]
 [ 12.3   12.28]
 [ 12.02  11.82]
 [ 12.15  11.96]
 [ 12.19  12.14]
 [ 12.07  12.02]
 [ 12.2   11.91]
 [ 12.19  12.18]
 [ 12.68  12.47]
 [ 12.88  12.59]
 [ 12.74  12.65]
 [ 13.    12.94]
 [ 13.05  12.71]
 [ 12.94  12.41]
 [ 12.95  12.95]
 [ 13.47  13.32]
 [ 13.27  12.87]
 [ 13.85  13.74]]
