# Tensorflow Basic

In [14]:
import tensorflow as tf

In [2]:
x = tf.constant(2)
y = tf.constant(4)

In [3]:
with tf.Session() as sess:
    print("x: %i" % sess.run(x), "y: %i" % sess.run(y))
    print("Addition with constants: %i" % sess.run(x+y))
    print("Multiplication with constants: %i" % sess.run(x*y))

x: 2 y: 4
Addition with constants: 6
Multiplication with constants: 8


In [4]:
add = tf.add(x, y)
sess = tf.Session()
value_of_add = sess.run(add)
print(value_of_add)
sess.close()

6


In [5]:
sub = tf.subtract(x, y)
sess = tf.Session()
value_of_sub = sess.run(sub)
print(value_of_sub)
sess.close()

-2


In [6]:
mult = tf.multiply(x, y)
sess = tf.Session()
value_of_mult = sess.run(mult)
print(value_of_mult)
sess.close()

8


In [7]:
div = tf.divide(x, y)
sess = tf.Session()
value_of_div = sess.run(div)
print(value_of_div)
sess.close()

0.5


In [8]:
# y = W.x + b
x = tf.constant(-2.0, name="x", dtype=tf.float32)
W = tf.constant(8.0, name="W", dtype=tf.float32)
b = tf.constant(10.0, name="b", dtype=tf.float32)

y = tf.Variable(tf.add(tf.multiply(W, x), b))

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print(session.run(y))   

-6.0


In [9]:
a = tf.constant(2.8)
b = tf.constant(4.3)

# Basic Math
total = a + b
diff = a - b
quot = tf.div(a, b)
prod = tf.multiply(a, b)

# Matrix Multiplication
c = tf.constant([[1,2], [3,4], [5,6]])
d = tf.constant([[9,8,7], [6,5,4]])
matrix_prod = tf.matmul(c, d)

# Excute the Session
with tf.Session() as sess:
    print("Sum: %f" % sess.run(total))
    print("Difference: %f" % sess.run(diff))
    print("Division: %f" % sess.run(quot))
    print("Multiplication: %f" % sess.run(prod))
    print("Matrix prouct: ",  sess.run(matrix_prod))
    print("Round: %f" % sess.run(tf.round(a)))
    print("Round: %f" % sess.run(tf.round(b)))

Sum: 7.100000
Difference: -1.500000
Division: 0.651163
Multiplication: 12.040000
Matrix prouct:  [[21 18 15]
 [51 44 37]
 [81 70 59]]
Round: 3.000000
Round: 4.000000


In [10]:
# 2-D tensor
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

with tf.Session() as sess:
    print("2-D tensor:")
    print(sess.run(a))

2-D tensor:
[[1 2 3]
 [4 5 6]]


In [11]:
# 2-D tensor
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

with tf.Session() as sess:
    print("2-D tensor:")
    print(sess.run(b))

2-D tensor:
[[ 7  8]
 [ 9 10]
 [11 12]]


In [12]:
c = tf.matmul(a, b)

with tf.Session() as sess:
    print("a * b:")
    print(sess.run(c))

a * b:
[[ 58  64]
 [139 154]]


In [13]:
# 3-D tensor
import numpy as np
x = tf.constant(np.arange(1, 13, dtype=np.int32),
                shape=[2, 2, 3])

y = tf.constant(np.arange(13, 25, dtype=np.int32),
                shape=[2, 3, 2])

z = tf.constant(np.arange(1, 13, dtype=np.int32),
                shape=[2, 2, 3])

with tf.Session() as sess:
    print("3-D tensor:")
    print('--------------------')
    print(sess.run(x))
    print('--------------------')
    print(sess.run(y))
    print('--------------------')
    print('3-D Multiplication:')
    print(sess.run(tf.matmul(x,y)))
    print('--------------------')
    print('Dot Product:')
    print(sess.run(tf.tensordot(x,z, 3)))

3-D tensor:
--------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
--------------------
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
--------------------
3-D Multiplication:
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]]
--------------------
Dot Product:
650
