# Least-Angled Regression (LARS)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# yfinance is used to fetch data
import yfinance as yf
yf.pdr_override()

In [2]:
# input
symbol = 'AMD'
start = '2014-01-01'
end = '2018-08-27'

# Read data 
dataset = yf.download(symbol,start,end)

# View Columns
dataset.head()

[*********************100%***********************]  1 of 1 completed


Adj Close  Close  High   Low  Open    Volume
Date                                                    
2014-01-02       3.95   3.95  3.98  3.84  3.85  20548400
2014-01-03       4.00   4.00  4.00  3.88  3.98  22887200
2014-01-06       4.13   4.13  4.18  3.99  4.01  42398300
2014-01-07       4.18   4.18  4.25  4.11  4.19  42932100
2014-01-08       4.18   4.18  4.26  4.14  4.23  30678700

In [3]:
dataset = dataset.reset_index()
dataset.head()

Date  Adj Close  Close  High   Low  Open    Volume
0 2014-01-02       3.95   3.95  3.98  3.84  3.85  20548400
1 2014-01-03       4.00   4.00  4.00  3.88  3.98  22887200
2 2014-01-06       4.13   4.13  4.18  3.99  4.01  42398300
3 2014-01-07       4.18   4.18  4.25  4.11  4.19  42932100
4 2014-01-08       4.18   4.18  4.26  4.14  4.23  30678700

In [4]:
dataset['Increase_Decrease'] = np.where(dataset['Volume'].shift(-1) > dataset['Volume'],1,0)
dataset['Buy_Sell_on_Open'] = np.where(dataset['Open'].shift(-1) > dataset['Open'],1,0)
dataset['Buy_Sell'] = np.where(dataset['Adj Close'].shift(-1) > dataset['Adj Close'],1,0)
dataset['Returns'] = dataset['Adj Close'].pct_change()
dataset = dataset.dropna()

In [5]:
dataset.tail()

Date  Adj Close      Close   High        Low       Open     Volume  \
1166 2018-08-20  19.980000  19.980000  20.08  19.350000  19.790001   62983200   
1167 2018-08-21  20.400000  20.400000  20.42  19.860001  19.980000   55629000   
1168 2018-08-22  20.900000  20.900000  20.92  20.209999  20.280001   62002700   
1169 2018-08-23  22.290001  22.290001  22.32  21.139999  21.190001  113444100   
1170 2018-08-24  23.980000  23.980000  24.00  22.670000  22.910000  164328200   

      Increase_Decrease  Buy_Sell_on_Open  Buy_Sell   Returns  
1166                  0                 1         1  0.010622  
1167                  1                 1         1  0.021021  
1168                  1                 1         1  0.024510  
1169                  1                 1         1  0.066507  
1170                  0                 0         0  0.075819

In [6]:
from sklearn import linear_model

In [7]:
X = np.array(dataset['Returns']).reshape(1, -1)
y = np.array(dataset['Adj Close']).reshape(1, -1)

In [8]:
reg = linear_model.Lars(n_nonzero_coefs=1)

In [9]:
reg.fit(X, y)

Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True,
   fit_path=True, n_nonzero_coefs=1, normalize=True, positive=False,
   precompute='auto', verbose=False)

In [10]:
print(reg.coef_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.20, random_state = 0) 

In [12]:
y_pred = reg.predict(X_test)

In [13]:
reg.coef_

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
reg.coef_[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
reg.score(X, y)

1.0