# Mini-Batch k-Means Clustering

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

# fetch yahoo data
import yfinance as yf
yf.pdr_override()

In [2]:
# input
symbol = 'AMD'
start = '2014-01-01'
end = '2018-08-27'

# Read data 
dataset = yf.download(symbol,start,end)

# Only keep close columns 
dataset.head()

[*********************100%***********************]  1 of 1 completed


Adj Close  Close  High   Low  Open    Volume
Date                                                    
2014-01-02       3.95   3.95  3.98  3.84  3.85  20548400
2014-01-03       4.00   4.00  4.00  3.88  3.98  22887200
2014-01-06       4.13   4.13  4.18  3.99  4.01  42398300
2014-01-07       4.18   4.18  4.25  4.11  4.19  42932100
2014-01-08       4.18   4.18  4.26  4.14  4.23  30678700

In [3]:
dataset['Increase_Decrease'] = np.where(dataset['Volume'].shift(-1) > dataset['Volume'],1,0)
dataset['Buy_Sell_on_Open'] = np.where(dataset['Open'].shift(-1) > dataset['Open'],1,0)
dataset['Buy_Sell'] = np.where(dataset['Adj Close'].shift(-1) > dataset['Adj Close'],1,0)
dataset['Returns'] = dataset['Adj Close'].pct_change()
dataset = dataset.dropna()

In [4]:
dataset.tail()

Adj Close      Close   High        Low       Open     Volume  \
Date                                                                       
2018-08-20  19.980000  19.980000  20.08  19.350000  19.790001   62983200   
2018-08-21  20.400000  20.400000  20.42  19.860001  19.980000   55629000   
2018-08-22  20.900000  20.900000  20.92  20.209999  20.280001   62002700   
2018-08-23  22.290001  22.290001  22.32  21.139999  21.190001  113444100   
2018-08-24  23.980000  23.980000  24.00  22.670000  22.910000  164328200   

            Increase_Decrease  Buy_Sell_on_Open  Buy_Sell   Returns  
Date                                                                 
2018-08-20                  0                 1         1  0.010622  
2018-08-21                  1                 1         1  0.021021  
2018-08-22                  1                 1         1  0.024510  
2018-08-23                  1                 1         1  0.066507  
2018-08-24                  0                 0         0  0.075819

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import MiniBatchKMeans

In [6]:
X = dataset.drop(['Adj Close', 'Open'], axis=1).values
Y = dataset['Adj Close'].values

In [7]:
# Standarize features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [8]:
# Create k-mean object
clustering = MiniBatchKMeans(n_clusters=1, random_state=0, batch_size=100)

# Train model
model = clustering.fit(X_std)

In [9]:
model.cluster_centers_

array([[ 0.02933401,  0.02995775,  0.02990656,  0.03856886, -0.0082592 ,
         0.00150837,  0.03229768,  0.02362391]])

In [10]:
model.labels_

array([0, 0, 0, ..., 0, 0, 0])

In [11]:
model.predict(X,Y)

array([0, 0, 0, ..., 0, 0, 0])