# Passive Aggressive Classifier

PassiveAggressiveClassifier is for binary classification

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

# fix_yahoo_finance is used to fetch data 
import fix_yahoo_finance as yf
yf.pdr_override()

In [2]:
# input
symbol = 'AMD'
start = '2014-01-01'
end = '2018-08-27'

# Read data 
dataset = yf.download(symbol,start,end)

# View Columns
dataset.head()

[*********************100%***********************]  1 of 1 downloaded


Open  High   Low  Close  Adj Close    Volume
Date                                                    
2014-01-02  3.85  3.98  3.84   3.95       3.95  20548400
2014-01-03  3.98  4.00  3.88   4.00       4.00  22887200
2014-01-06  4.01  4.18  3.99   4.13       4.13  42398300
2014-01-07  4.19  4.25  4.11   4.18       4.18  42932100
2014-01-08  4.23  4.26  4.14   4.18       4.18  30678700

In [3]:
dataset = dataset.reset_index()

In [4]:
dataset['Increase_Decrease'] = np.where(dataset['Volume'].shift(-1) > dataset['Volume'],'Increase','Decrease')
dataset['Buy_Sell_on_Open'] = np.where(dataset['Open'].shift(-1) > dataset['Open'],1,0)
dataset['Buy_Sell'] = np.where(dataset['Adj Close'].shift(-1) > dataset['Adj Close'],1,0)
dataset['Return'] = dataset['Adj Close'].pct_change()
dataset = dataset.dropna()
dataset.head()

Date  Open  High   Low  Close  Adj Close    Volume Increase_Decrease  \
1 2014-01-03  3.98  4.00  3.88   4.00       4.00  22887200          Increase   
2 2014-01-06  4.01  4.18  3.99   4.13       4.13  42398300          Increase   
3 2014-01-07  4.19  4.25  4.11   4.18       4.18  42932100          Decrease   
4 2014-01-08  4.23  4.26  4.14   4.18       4.18  30678700          Decrease   
5 2014-01-09  4.20  4.23  4.05   4.09       4.09  30667600          Decrease   

   Buy_Sell_on_Open  Buy_Sell    Return  
1                 1         1  0.012658  
2                 1         1  0.032500  
3                 1         0  0.012107  
4                 0         0  0.000000  
5                 0         1 -0.021531

In [5]:
dataset.tail()

Date       Open       High        Low      Close  Adj Close  \
1167 2018-08-21  19.980000  20.420000  19.860001  20.400000  20.400000   
1168 2018-08-22  20.280001  20.920000  20.209999  20.900000  20.900000   
1169 2018-08-23  21.190001  22.320000  21.139999  22.290001  22.290001   
1170 2018-08-24  22.910000  24.000000  22.670000  23.980000  23.980000   
1171 2018-08-27  24.940001  27.299999  24.629999  25.260000  25.260000   

         Volume Increase_Decrease  Buy_Sell_on_Open  Buy_Sell    Return  
1167   55629000          Increase                 1         1  0.021021  
1168   62002700          Increase                 1         1  0.024510  
1169  113444100          Increase                 1         1  0.066507  
1170  164328200          Increase                 1         1  0.075819  
1171  325058400          Decrease                 0         0  0.053378

In [6]:
dataset.shape

(1171, 11)

In [7]:
from sklearn.linear_model import PassiveAggressiveClassifier

In [8]:
X = np.array(dataset['Adj Close']).reshape(1171,-1)
Y = np.array(dataset['Buy_Sell']).reshape(1171,-1)

In [9]:
clf = PassiveAggressiveClassifier(max_iter=1000, random_state=0)
clf.fit(X, Y)

PassiveAggressiveClassifier(C=1.0, average=False, class_weight=None,
              fit_intercept=True, loss='hinge', max_iter=1000, n_iter=None,
              n_jobs=1, random_state=0, shuffle=True, tol=None, verbose=0,
              warm_start=False)

In [10]:
clf.coef_

array([[0.34290469]])

In [11]:
clf.intercept_

array([-0.21990147])

In [12]:
clf.score(X,Y)

0.4995730145175064

In [15]:
clf.predict(Y)

array([1, 1, 0, ..., 1, 1, 0])